== CONVERTER

=== Dictionary converter tools

There are a couple of tools to convert several dictionary data into XML files that can be used by xml2eb.
Now there are two tools supporting  following dictionaries:

* link:http://www.wdic.org/[通信用語(等)の基礎知識 (汎用辞書 V6 format)]

* link:http://www.post.japanpost.jp/zipcode/download.html[Zip Code data]


=== 通信用語(等)の基礎知識用変換ツール(conv-wdic)について

==== Usage

`$ bin/conv-wdic.sh [Dictionary Data directory]`

After execute the command, the tool generate book.xml in a dictionary directory.
It is necessary to prepare the dictionary directory as same as follows:

[ditaa]
....
+-------------------------+
|Dictionary data directory|
+----+--------------------+
     |
     +-----------------+
     | dictionary data |
     +-----------------+
     |
     +--------------------------------------------------+
     |  gaiji (Store Gaiji font generated by converter) |
     +--------------------------------------------------+
     |
     +---------------------------------------------------+
     |  table (Store table data generated by converter)  |
     +---------------------------------------------------+
     |
     +---------+
     |  plugin |
     +----+----+
     |    |
     |    +------------+
     |    |plugin data |
     |    +------------+
     +--------+
     |  glyph |
     +----+---+
          |
          +------------+
          | glyph data |
          +------------+
....

Note: It is not necessary to make gaiji and table directory because there are automatically genearted by the converter tool.

It is necessary to complete following conditions for plugin data:

Image::
  There exist a bmp file that related to a png file.
         (A filename should be *.png.bmp)

Sound::
  There exist a wav file that related to a mp3/ogg file.
         (A filename should be *.mp3.wav/*.ogg.wav)

Text::
  Text file is encoded by UTF-8.

Glyph::
  Glyph image data is an image that related to +\\glyph\{code\} function in dictionary data.
  The image data should have a name in form of +"code.50px.png.bmp" .
  It is necessary to generate it from dictionary data in advance to running a tool.
  You can find PNG images in  link:http://glyphwiki.org/[グリフウィキ(GlyphWiki)] site.
  Please convert it to BMP.
  Sample URL of image is "http://glyphwiki.org/glyph/code.50px.png"

GAIJI::
  A Character set in Ebook is limited to JIS X0208 because of JIS X4081 specification.
  It is because it cannot express all characters in Unicode specification..
  So a tool generate GAIJI images for characters which are not supported.
  It is also limited to express table, the tool generate image of table.
  To generate GAIJI and table, you need to specify font for the tool.
  Please edit wdic-fonts.properties file.


=== 郵便番号用変換ツール(conv-zipcode)について

==== Usage:

`$ bin/conv-zipcode.sh [データディレクトリ]`

After execute the command, the tool generate book.xml in a dictionary directory.
It is necessary to prepare the dictionary directory as same as follows:

[ditaa]
....
+----------------+
| Data Directory |
+----+-----------+
     |
     +---------------+
     |  KEN_ALL.CSV  |
     +---------------+
     |
     +----------------+
     | JIGYOSYO.CSV   |
     +----------------+
....


